# Generated by Django 4.1.3 on 2022-11-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_store_custo_first_n_a7e990_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='store_custo_first_n_8f83e0_idx',
            old_name='store_custo_first_n_a7e990_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='store_custo_email_8208ee_idx',
            old_name='store_custo_email_c4e0e9_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
